# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://git.coding.net/CocoaPods/Specs.git'
target 'ota' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Alamofire' 

  # Pods for ota

  target 'otaTests' do
    inherit! :search_paths
	# Pods for testing
  end

  target 'otaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
